swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /api
paths:
  /devops/constant/{key}:
    get:
      tags:
      - devops
      description: '获取静态数据列表 key : applications/envs/engineRoom'
      operationId: ServerController.get applications
      responses:
        "200":
          description: 'like this:  { result: ["aa", "bb", "cc"] }'
        "400":
          description: service exception
  /devops/servers:
    get:
      tags:
      - devops
      description: 查询列表， result 结构为 serverDTO 数组
      operationId: ServerController.create server
      parameters:
      - in: query
        name: page
        description: 页码, 缺省：1
        type: integer
        format: int64
      - in: query
        name: pageSize
        description: 步长, 缺省:15
        type: integer
        format: int64
      - in: query
        name: application
        description: 应用
        type: string
      - in: query
        name: engineRoom
        description: 机房
        type: string
      - in: query
        name: env
        description: 环境
        type: integer
        format: int64
      - in: query
        name: ip
        description: ip
        type: string
      responses:
        "200":
          description: 'resultsVO:  { "count": 0, "results": [ serverDTO ] }'
        "400":
          description: service exception
    post:
      tags:
      - devops
      operationId: ServerController.create server
      parameters:
      - in: formData
        name: tag
        description: 名称标签
        required: true
        type: string
      - in: formData
        name: env
        description: 环境
        type: string
      - in: formData
        name: engineRoom
        description: 机房
        required: true
        type: string
      - in: formData
        name: core
        description: 核心数
        required: true
        type: integer
        format: int64
      - in: formData
        name: memory
        description: 内存数
        required: true
        type: integer
        format: int64
      - in: formData
        name: intranetIp
        description: 内网ip
        type: string
      - in: formData
        name: extranetIp
        description: 外网ip
        type: string
      - in: formData
        name: remark
        description: 备注
        type: string
      - in: formData
        name: users
        description: 用户
        required: true
        schema:
          $ref: '#/definitions/.User'
      - in: formData
        name: disks
        description: 磁盘
        required: true
        schema:
          $ref: '#/definitions/.Disk'
      responses:
        "200":
          description: '{status: success}'
        "400":
          description: service exception
    delete:
      tags:
      - devops
      description: 删除server信息
      operationId: ServerController.delete server
      parameters:
      - in: formData
        name: ids
        description: 'json like this: {ids: [2,3,4,5,6]}'
        required: true
        type: array
        items:
          type: integer
          format: int64
      responses:
        "200":
          description: '{status: "success"}'
        "400":
          description: 400 service exception
  /devops/servers/{id}:
    get:
      tags:
      - devops
      description: 查询server信息
      operationId: ServerController.find server
      parameters:
      - in: path
        name: id
        description: server id
        required: true
        type: integer
        format: int64
      responses:
        "200":
          schema:
            $ref: '#/definitions/devops.ServerDTO'
        "400":
          description: 400 service exception
    put:
      tags:
      - devops
      operationId: ServerController.create server
      parameters:
      - in: formData
        name: tag
        description: 名称标签
        required: true
        type: string
      - in: formData
        name: env
        description: 环境
        type: string
      - in: formData
        name: engineRoom
        description: 机房
        required: true
        type: string
      - in: formData
        name: core
        description: 核心数
        required: true
        type: integer
        format: int64
      - in: formData
        name: memory
        description: 内存数
        required: true
        type: integer
        format: int64
      - in: formData
        name: intranetIp
        description: 内网ip
        type: string
      - in: formData
        name: extranetIp
        description: 外网ip
        type: string
      - in: formData
        name: remark
        description: 备注
        type: string
      - in: formData
        name: users
        description: 用户
        required: true
        schema:
          $ref: '#/definitions/.User'
      - in: formData
        name: disks
        description: 磁盘
        required: true
        schema:
          $ref: '#/definitions/.Disk'
      responses:
        "200":
          description: '{status: success}'
        "400":
          description: service exception
    delete:
      tags:
      - devops
      description: 删除server信息
      operationId: ServerController.delete server
      parameters:
      - in: path
        name: id
        description: server id
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: '{status: "success"}'
        "400":
          description: 400 service exception
  /devops/servings:
    get:
      tags:
      - devops
      operationId: ServingController.查询服务列表
      parameters:
      - in: query
        name: page
        description: 页码, 缺省：1
        type: integer
        format: int64
      - in: query
        name: pageSize
        description: 步长, 缺省:15
        type: integer
        format: int64
      - in: query
        name: application
        description: 应用
        type: string
      - in: query
        name: engineRoom
        description: 机房
        type: string
      - in: query
        name: env
        description: 环境
        type: integer
        format: int64
      - in: query
        name: ip
        description: ip
        type: string
      responses:
        "200":
          schema:
            type: array
            items:
              $ref: '#/definitions/devops.ServingDTO'
        "400":
          description: service exception
    post:
      tags:
      - devops
      operationId: ServingController.创建服务
      parameters:
      - in: formData
        name: tag
        description: 名称标签
        required: true
        type: string
      - in: formData
        name: serverIds
        description: 服务器ids 数组
        type: array
        items:
          type: integer
          format: int64
      - in: formData
        name: application
        description: 应用
        required: true
        type: string
      - in: formData
        name: url
        description: URL
        type: string
      - in: formData
        name: version
        description: 版本
        required: true
        type: string
      - in: formData
        name: dependency
        description: 依赖
        type: string
      - in: formData
        name: remark
        description: 备注
        type: string
      responses:
        "200":
          description: '{status: success}'
        "400":
          description: service exception
    delete:
      tags:
      - devops
      description: 删除server信息
      operationId: ServingController.delete serving
      parameters:
      - in: formData
        name: ids
        description: 'json like this: {ids: [2,3,4,5,6]}'
        required: true
        type: array
        items:
          type: integer
          format: int64
      responses:
        "200":
          description: '{status: "success"}'
        "400":
          description: 400 service exception
  /devops/servings/{id}:
    get:
      tags:
      - devops
      operationId: ServingController.查找一个服务
      parameters:
      - in: query
        name: id
        description: service id
        required: true
        type: integer
        format: int64
      responses:
        "200":
          schema:
            $ref: '#/definitions/devops.ServingDetailDTO'
        "400":
          description: service exception
    put:
      tags:
      - devops
      operationId: ServingController.查找一个服务
      parameters:
      - in: query
        name: id
        description: id
        required: true
        type: integer
        format: int64
      - in: formData
        name: tag
        description: 名称标签
        required: true
        type: string
      - in: formData
        name: serverIds
        description: 服务器ids 数组
        type: array
        items:
          type: integer
          format: int64
      - in: formData
        name: application
        description: 应用
        required: true
        type: string
      - in: formData
        name: url
        description: URL
        type: string
      - in: formData
        name: version
        description: 版本
        required: true
        type: string
      - in: formData
        name: dependency
        description: 依赖
        type: string
      - in: formData
        name: remark
        description: 备注
        type: string
      responses:
        "200":
          description: '{status: success}'
        "400":
          description: service exception
    delete:
      tags:
      - devops
      description: 删除server信息
      operationId: ServingController.delete serving
      parameters:
      - in: path
        name: id
        description: server id
        required: true
        type: integer
        format: int64
      responses:
        "200":
          description: '{status: "success"}'
        "400":
          description: 400 service exception
definitions:
  .Disk:
    type: object
  .User:
    type: object
  devops.DiskDTO:
    title: DiskDTO
    type: object
    properties:
      id:
        type: integer
        format: int64
      rootPath:
        type: string
      serverId:
        type: integer
        format: int64
      size:
        type: integer
        format: int64
  devops.ServerDTO:
    title: ServerDTO
    type: object
    properties:
      applications: {}
      core:
        type: integer
        format: int64
      createdDate:
        type: string
      disks:
        type: array
        items:
          $ref: '#/definitions/devops.DiskDTO'
      engineRoom:
        type: string
      env:
        type: string
      extranetIp:
        type: string
      id:
        type: integer
        format: int64
      intranetIp:
        type: string
      memory:
        type: integer
        format: int64
      remark:
        type: string
      serverId:
        type: string
      tag:
        type: string
      updatedDate:
        type: string
      users:
        type: array
        items:
          $ref: '#/definitions/devops.UserDTO'
  devops.ServingDTO:
    title: ServingDTO
    type: object
    properties:
      application:
        type: string
      createdDate:
        type: string
      dependency:
        type: string
      id:
        type: integer
        format: int64
      remark:
        type: string
      tag:
        type: string
      updatedDate:
        type: string
      url:
        type: string
      version:
        type: string
  devops.ServingDetailDTO:
    title: ServingDetailDTO
    type: object
    properties:
      application:
        type: string
      createdDate:
        type: string
      dependency:
        type: string
      id:
        type: integer
        format: int64
      remark:
        type: string
      servers:
        type: array
        items:
          $ref: '#/definitions/devops.SimpleServerDTO'
      tag:
        type: string
      updatedDate:
        type: string
      url:
        type: string
      version:
        type: string
  devops.SimpleServerDTO:
    title: SimpleServerDTO
    type: object
    properties:
      Tag:
        type: string
      core:
        type: integer
        format: int64
      engineRoom:
        type: string
      env:
        type: string
      extranetIp:
        type: string
      id:
        type: integer
        format: int64
      memory:
        type: integer
        format: int64
      serverId:
        type: string
  devops.UserDTO:
    title: UserDTO
    type: object
    properties:
      id:
        type: integer
        format: int64
      password:
        type: string
      serverId:
        type: integer
        format: int64
      userName:
        type: string
tags:
- name: devops
  description: |
    服务相关接口
